// app/web/vue/src/projects/client/components/funding/depositModal/components/CreditCardForm.vue
<template>
  <div class="credit-card-form mt-7">
    <h2 class="[ t-lin t-lin--dot]">{{ t("fields.creditCard") }}</h2>
    <form @submit="onSubmit">
      <div class="form-group">
        <label for="ccNumber">{{ t("fields.ccNumber") }}</label>
        <div class="card-number-input">
          <Field
            name="ccNumber"
            type="text"
            id="ccNumber"
            placeholder="1234 5678 9012 3456"
            v-model="paymentRequireData.request.ccNumber"
          />
          <div class="card-icons">
            <img src="/images/wallet/visa.png" alt="Visa" />
            <img src="/images/wallet/mastercard.png" alt="MasterCard" />
            <img src="/images/wallet/amex.png" alt="American Express" />
            <img src="/images/wallet/discover.png" alt="Discover" />
          </div>
        </div>
        <ErrorMessage name="ccNumber" />
      </div>
      <div class="form-group name-inputs row">
        <div class="col-6">
          <label for="billingFirstName">{{ t("fields.firstName") }}</label>
          <Field
            name="billingFirstName"
            type="text"
            id="billingFirstName"
            v-model="paymentRequireData.request.billingFirstName"
          />
          <ErrorMessage name="billingFirstName" />
        </div>
        <div class="col-6">
          <label for="billingLastName">{{ t("fields.lastName") }}</label>
          <Field
            name="billingLastName"
            type="text"
            id="billingLastName"
            v-model="paymentRequireData.request.billingLastName"
          />
          <ErrorMessage name="billingLastName" />
        </div>
      </div>
      <div class="form-group expiry-cvv-inputs row mb-11">
        <div class="col-4">
          <label for="ccCvc">{{ t("fields.ccCvc") }}</label>
          <Field
            name="ccCvc"
            type="text"
            id="ccCvc"
            placeholder="CVV"
            class="h-45px"
            v-model="paymentRequireData.request.ccCvc"
          />
          <ErrorMessage name="ccCvc" />
        </div>
        <div class="col-4">
          <label for="ccMonth">{{ t("fields.ccMonth") }}</label>
          <Field
            as="select"
            name="ccMonth"
            id="ccMonth"
            class="h-45px"
            v-model="paymentRequireData.request.ccMonth"
          >
            <option value="" disabled>--</option>
            <option
              v-for="month in months"
              :key="month.value"
              :value="month.value"
            >
              {{ month.text }}
            </option>
          </Field>
          <ErrorMessage name="ccMonth" />
        </div>
        <div class="col-4">
          <label for="ccYear">{{ t("fields.ccYear") }}</label>
          <Field
            as="select"
            name="ccYear"
            id="ccYear"
            class="h-45px"
            v-model="paymentRequireData.request.ccYear"
          >
            <option value="" disabled>--</option>
            <option v-for="year in years" :key="year" :value="year">
              {{ year }}
            </option>
          </Field>
          <ErrorMessage name="ccYear" />
        </div>
      </div>
      <h2 class="[ t-lin t-lin--dot]">{{ t("fields.billingInformation") }}</h2>
      <div class="form-group">
        <label for="billingAddress">{{ t("fields.billingAddress") }}</label>
        <Field
          name="billingAddress"
          type="text"
          id="billingAddress"
          v-model="paymentRequireData.request.billingAddress"
        />
        <ErrorMessage name="billingAddress" />
      </div>
      <div class="form-group location-inputs row">
        <div class="col-3">
          <label for="billingCity">{{ t("fields.billingCity") }}</label>
          <Field
            name="billingCity"
            type="text"
            id="billingCity"
            v-model="paymentRequireData.request.billingCity"
          />
          <ErrorMessage name="billingCity" />
        </div>
        <div class="col-3">
          <label for="billingState">{{ t("fields.billingState") }}</label>
          <Field
            name="billingState"
            type="text"
            id="billingState"
            v-model="paymentRequireData.request.billingState"
          />
          <ErrorMessage name="billingState" />
        </div>
        <div class="col-3">
          <label for="billingZipcode">{{ t("fields.billingZipcode") }}</label>
          <Field
            name="billingZipcode"
            type="text"
            id="billingZipcode"
            v-model="paymentRequireData.request.billingZipcode"
          />
          <ErrorMessage name="billingZipcode" />
        </div>
        <div class="col-3">
          <label for="billingCountry">{{ t("fields.billingCountry") }}</label>
          <Field
            class="h-45px"
            as="select"
            name="billingCountry"
            id="billingCountry"
            v-model="paymentRequireData.request.billingCountry"
          >
            <option value="" disabled>--</option>
            <option
              v-for="(item, index) in regionCodes"
              :key="index"
              :label="item.name"
              :value="item.code"
            >
              {{ item.name }}
            </option>
          </Field>
          <ErrorMessage name="billingCountry" />
        </div>
      </div>
      <div class="form-group">
        <label for="billingPhone">{{ t("fields.userMobile") }}</label>
        <Field
          name="billingPhone"
          type="text"
          id="billingPhone"
          v-model="paymentRequireData.request.billingPhone"
        />
        <ErrorMessage name="billingPhone" />
      </div>
    </form>
  </div>
</template>

<script setup lang="ts">
import * as Yup from "yup";
import { useI18n } from "vue-i18n";
import { useForm, Field, ErrorMessage } from "vee-validate";
import { inject, ref } from "vue";
import { getRegionCodes } from "@/core/data/phonesData";

const paymentRequireData = inject<any>("paymentRequireData");
const { t } = useI18n();
const regionCodes = ref(getRegionCodes());
const months = [
  { value: "01", text: "1" },
  { value: "02", text: "2" },
  { value: "03", text: "3" },
  { value: "04", text: "4" },
  { value: "05", text: "5" },
  { value: "06", text: "6" },
  { value: "07", text: "7" },
  { value: "08", text: "8" },
  { value: "09", text: "9" },
  { value: "10", text: "10" },
  { value: "11", text: "11" },
  { value: "12", text: "12" },
];

const currentYear = new Date().getFullYear();
const years = Array.from({ length: 20 }, (_, i) => currentYear + i);

const validationSchema = Yup.object().shape({
  ccNumber: Yup.string().required(t("tip.requiredField")),
  billingFirstName: Yup.string().required(t("tip.requiredField")),
  ccMonth: Yup.string().required(t("tip.requiredField")),
  ccYear: Yup.string().required(t("tip.requiredField")),
  ccCvc: Yup.string().required(t("tip.requiredField")).max(3, "3 Max"),
  billingAddress: Yup.string()
    .required(t("tip.requiredField"))
    .max(200, "200 Max"),
  billingCity: Yup.string()
    .required(t("tip.requiredField"))
    .max(100, "100 Max"),
  billingState: Yup.string().when("billingCountry", {
    is: "us",
    then: Yup.string().required(t("tip.requiredField")).max(3, "3 Max"),
    otherwise: Yup.string().max(3, "3 Max"),
  }),
  billingZipcode: Yup.string()
    .required(t("tip.requiredField"))
    .max(12, "12 Max"),
  billingCountry: Yup.string().required(t("tip.requiredField")),
  billingPhone: Yup.string().required(t("tip.requiredField")).max(25, "25 Max"),
});

const { handleSubmit } = useForm({
  validationSchema,
});

const onSubmit = handleSubmit((values) => {
  if (values.billingState === undefined || values.billingState === "") {
    values.billingState = "N/A";
  }
  if (values.billingLastName === undefined || values.billingLastName === "") {
    values.billingLastName = "N/A";
  }

  return true;
});

defineExpose({
  onSubmit,
});
</script>

<style scoped>
h2 {
  text-align: center;
  margin-bottom: 20px;
}

.form-group {
  margin-bottom: 20px;
}

.form-group label {
  display: block;
  margin-bottom: 5px;
  font-weight: bold;
}

.form-group input,
.form-group select {
  width: 100%;
  padding: 10px;
  box-sizing: border-box;
  border: 1px solid #ccc;
  border-radius: 5px;
}

.form-group .name-inputs,
.form-group .expiry-cvv-inputs,
.form-group .location-inputs {
  display: flex;
  gap: 10px;
}

.form-group .name-inputs div,
.form-group .expiry-cvv-inputs div,
.form-group .location-inputs div {
  flex: 1;
}

.form-group .card-number-input {
  display: flex;
  align-items: center;
  gap: 10px;
}

.form-group .card-icons {
  display: flex;
  gap: 5px;
}

.form-group .card-icons img {
  width: 40px;
  height: auto;
}

.form-group span {
  color: red;
  font-size: 12px;
  margin-top: 5px;
  display: block;
}

button {
  width: 100%;
  padding: 15px;
  background-color: #007bff;
  color: white;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  font-size: 16px;
}

button:hover {
  background-color: #0056b3;
}

.t-lin {
  display: table;
  white-space: nowrap;
  padding: 0 0.8em;
}
.t-lin:before,
.t-lin:after {
  content: "";
  display: table-cell;
  position: relative;
  top: 0.5em;
  width: 50%;
  border-top: 1px solid;
}
.t-lin:before {
  right: 0.8em;
}
.t-lin:after {
  left: 0.8em;
}

.t-lin--dot:before,
.t-lin--dot:after {
  top: 0.4em;
  border-top: 4px dotted;
}
</style>

// app/web/react/src/components/dashboard/modals/CreditCardForm.tsx
'use client';

import { forwardRef, useImperativeHandle, useMemo, useState, useCallback } from 'react';
import Image from 'next/image';
import { useTranslations } from 'next-intl';
import { Input, SimpleSelect, SearchableSelect } from '@/components/ui';
import { getRegionCodes } from '@/core/data/phonesData';

export interface CreditCardFormHandle {
  /** 触发校验，校验通过返回处理后的字段（含 N/A 兜底），未通过返回 null */
  validate: () => Record<string, string> | null;
}

export interface CreditCardFormProps {
  value: Record<string, string>;
  onChange: (key: string, value: string) => void;
  disabled?: boolean;
}

interface FieldConfig {
  required?: boolean;
  maxLength?: number;
  /** 当 billingCountry === 'us' 时才必填 */
  requiredWhenUS?: boolean;
}

const FIELD_RULES: Record<string, FieldConfig> = {
  ccNumber: { required: true },
  billingFirstName: { required: true },
  ccMonth: { required: true },
  ccYear: { required: true },
  ccCvc: { required: true, maxLength: 3 },
  billingAddress: { required: true, maxLength: 200 },
  billingCity: { required: true, maxLength: 100 },
  billingState: { requiredWhenUS: true, maxLength: 3 },
  billingZipcode: { required: true, maxLength: 12 },
  billingCountry: { required: true },
  billingPhone: { required: true, maxLength: 25 },
};

const MONTH_OPTIONS = Array.from({ length: 12 }, (_, i) => {
  const v = String(i + 1).padStart(2, '0');
  return { value: v, label: String(i + 1) };
});

export const CreditCardForm = forwardRef<CreditCardFormHandle, CreditCardFormProps>(
  function CreditCardForm({ value, onChange, disabled }, ref) {
    const t = useTranslations('deposit.creditCard');
    const tDeposit = useTranslations('deposit');
    const [errors, setErrors] = useState<Record<string, string>>({});

    // 国家选项
    const countryOptions = useMemo(() => {
      const regions = getRegionCodes();
      return Object.entries(regions).map(([code, country]) => ({
        value: code,
        label: country.name,
      }));
    }, []);

    // 年份选项 - 当前年起 20 年
    const yearOptions = useMemo(() => {
      const currentYear = new Date().getFullYear();
      return Array.from({ length: 20 }, (_, i) => {
        const y = String(currentYear + i);
        return { value: y, label: y };
      });
    }, []);

    const setError = useCallback((key: string, msg: string) => {
      setErrors((prev) => ({ ...prev, [key]: msg }));
    }, []);

    const clearError = useCallback((key: string) => {
      setErrors((prev) => {
        if (!prev[key]) return prev;
        const next = { ...prev };
        delete next[key];
        return next;
      });
    }, []);

    const handleFieldChange = useCallback(
      (key: string, val: string) => {
        onChange(key, val);
        if (errors[key]) clearError(key);
      },
      [onChange, errors, clearError]
    );

    useImperativeHandle(ref, () => ({
      validate: () => {
        const newErrors: Record<string, string> = {};
        const country = (value.billingCountry || '').toLowerCase();

        for (const [key, rule] of Object.entries(FIELD_RULES)) {
          const v = (value[key] ?? '').toString().trim();

          // 必填校验（含按国家条件必填）
          const isRequired = rule.required || (rule.requiredWhenUS && country === 'us');
          if (isRequired && !v) {
            newErrors[key] = tDeposit('error.requiredField');
            continue;
          }

          // 长度校验
          if (rule.maxLength && v.length > rule.maxLength) {
            newErrors[key] = tDeposit('error.maxLength', { max: rule.maxLength });
          }
        }

        setErrors(newErrors);

        if (Object.keys(newErrors).length > 0) {
          return null;
        }

        // billingState / billingLastName 为空时填 N/A 兜底
        const finalValues: Record<string, string> = { ...value };
        if (!finalValues.billingState?.trim()) finalValues.billingState = 'N/A';
        if (!finalValues.billingLastName?.trim()) finalValues.billingLastName = 'N/A';

        return finalValues;
      },
    }), [value, tDeposit]);

    return (
      <div className="flex flex-col gap-5">
        {/* 信用卡信息分组 */}
        <SectionDivider>{t('title')}</SectionDivider>

        {/* 卡号 + 卡片图标 */}
        <div className="flex flex-col gap-2">
          <label className="flex items-center text-sm font-medium text-text-secondary">
            <span className="mr-0.5 text-primary">*</span>
            {t('ccNumber')}
          </label>
          <div className="flex items-center gap-3">
            <Input
              inputSize="md"
              value={value.ccNumber || ''}
              onChange={(e) => handleFieldChange('ccNumber', e.target.value)}
              disabled={disabled}
              placeholder="1234 5678 9012 3456"
              error={errors.ccNumber}
              errorPosition="bottom"
            />
            <CardBrandIcons />
          </div>
        </div>

        {/* 名 / 姓 */}
        <div className="flex flex-row gap-4">
          <div className="flex-1">
            <Input
              label={t('firstName')}
              required
              inputSize="md"
              value={value.billingFirstName || ''}
              onChange={(e) => handleFieldChange('billingFirstName', e.target.value)}
              disabled={disabled}
              error={errors.billingFirstName}
              errorPosition="bottom"
            />
          </div>
          <div className="flex-1">
            <Input
              label={t('lastName')}
              inputSize="md"
              value={value.billingLastName || ''}
              onChange={(e) => handleFieldChange('billingLastName', e.target.value)}
              disabled={disabled}
              error={errors.billingLastName}
              errorPosition="bottom"
            />
          </div>
        </div>

        {/* CVC / 月 / 年 */}
        <div className="flex flex-row gap-4">
          <div className="flex-1">
            <Input
              label={t('ccCvc')}
              required
              inputSize="md"
              value={value.ccCvc || ''}
              onChange={(e) => handleFieldChange('ccCvc', e.target.value)}
              disabled={disabled}
              placeholder="CVV"
              maxLength={3}
              error={errors.ccCvc}
              errorPosition="bottom"
            />
          </div>
          <div className="flex-1">
            <SelectField
              label={t('ccMonth')}
              required
              value={value.ccMonth || ''}
              onChange={(v) => handleFieldChange('ccMonth', v)}
              options={MONTH_OPTIONS}
              placeholder="--"
              disabled={disabled}
              error={errors.ccMonth}
            />
          </div>
          <div className="flex-1">
            <SelectField
              label={t('ccYear')}
              required
              value={value.ccYear || ''}
              onChange={(v) => handleFieldChange('ccYear', v)}
              options={yearOptions}
              placeholder="--"
              disabled={disabled}
              error={errors.ccYear}
            />
          </div>
        </div>

        {/* 账单信息分组 */}
        <SectionDivider>{t('billingInformation')}</SectionDivider>

        {/* 账单地址 */}
        <Input
          label={t('billingAddress')}
          required
          inputSize="md"
          value={value.billingAddress || ''}
          onChange={(e) => handleFieldChange('billingAddress', e.target.value)}
          disabled={disabled}
          maxLength={200}
          error={errors.billingAddress}
          errorPosition="bottom"
        />

        {/* 城市 / 州 / 邮编 / 国家 */}
        <div className="flex flex-row gap-4">
          <div className="flex-1">
            <Input
              label={t('billingCity')}
              required
              inputSize="md"
              value={value.billingCity || ''}
              onChange={(e) => handleFieldChange('billingCity', e.target.value)}
              disabled={disabled}
              maxLength={100}
              error={errors.billingCity}
              errorPosition="bottom"
            />
          </div>
          <div className="flex-1">
            <Input
              label={t('billingState')}
              required={(value.billingCountry || '').toLowerCase() === 'us'}
              inputSize="md"
              value={value.billingState || ''}
              onChange={(e) => handleFieldChange('billingState', e.target.value)}
              disabled={disabled}
              maxLength={3}
              error={errors.billingState}
              errorPosition="bottom"
            />
          </div>
          <div className="flex-1">
            <Input
              label={t('billingZipcode')}
              required
              inputSize="md"
              value={value.billingZipcode || ''}
              onChange={(e) => handleFieldChange('billingZipcode', e.target.value)}
              disabled={disabled}
              maxLength={12}
              error={errors.billingZipcode}
              errorPosition="bottom"
            />
          </div>
          <div className="flex-1">
            <div className="w-full">
              <div className="mb-2 flex items-center">
                <label className="flex items-center text-sm font-normal text-text-secondary">
                  <span className="mr-0.5 text-primary">*</span>
                  {t('billingCountry')}
                </label>
              </div>
              <SearchableSelect
                options={countryOptions}
                value={countryOptions.find((opt) => opt.value === value.billingCountry) || null}
                onChange={(option: unknown) => {
                  const selected = option as { value: string; label: string } | null;
                  handleFieldChange('billingCountry', selected?.value || '');
                }}
                placeholder="--"
                isDisabled={disabled}
                error={errors.billingCountry}
                errorPosition="bottom"
              />
            </div>
          </div>
        </div>

        {/* 联系电话 */}
        <Input
          label={t('billingPhone')}
          required
          inputSize="md"
          value={value.billingPhone || ''}
          onChange={(e) => handleFieldChange('billingPhone', e.target.value)}
          disabled={disabled}
          maxLength={25}
          error={errors.billingPhone}
          errorPosition="bottom"
        />
      </div>
    );
  }
);

function SectionDivider({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex items-center gap-3 text-text-primary">
      <span className="h-px flex-1 bg-border" />
      <span className="text-sm font-semibold">{children}</span>
      <span className="h-px flex-1 bg-border" />
    </div>
  );
}

const CARD_BRANDS: { src: string; alt: string }[] = [
  { src: '/images/wallet/visa.png', alt: 'Visa' },
  { src: '/images/wallet/mastercard.png', alt: 'MasterCard' },
  { src: '/images/wallet/amex.png', alt: 'American Express' },
  { src: '/images/wallet/discover.png', alt: 'Discover' },
];

function CardBrandIcons() {
  return (
    <div className="flex shrink-0 items-center gap-2">
      {CARD_BRANDS.map((b) => (
        <Image
          key={b.alt}
          src={b.src}
          alt={b.alt}
          width={40}
          height={24}
          className="h-6 w-auto object-contain"
        />
      ))}
    </div>
  );
}

interface SelectFieldProps {
  label: string;
  required?: boolean;
  value: string;
  onChange: (v: string) => void;
  options: { value: string; label: string }[];
  placeholder?: string;
  disabled?: boolean;
  error?: string;
  contentClassName?: string;
}

function SelectField({
  label,
  required,
  value,
  onChange,
  options,
  placeholder,
  disabled,
  error,
  contentClassName,
}: SelectFieldProps) {
  return (
    <div className="w-full">
      <div className="mb-2 flex items-center">
        <label className="flex items-center text-sm font-normal text-text-secondary">
          {required && <span className="mr-0.5 text-primary">*</span>}
          {label}
        </label>
      </div>
      <SimpleSelect
        value={value}
        onChange={onChange}
        options={options}
        placeholder={placeholder}
        disabled={disabled}
        error={!!error}
        triggerSize="md"
        contentClassName={contentClassName}
      />
      {error && <p className="error-text mt-1 text-sm">{error}</p>}
    </div>
  );
}
