// app/web/react/src/components/TimeShow.tsx
'use client';

import { useMemo } from 'react';
import moment from 'moment';
import { useUserStore } from '@/stores';

type TimeShowType =
  | 'inFields'
  | 'withoutSec'
  | 'GMTinFields'
  | 'GMToneLiner'
  | 'oneLiner'
  | 'customCSS'
  | 'customCSSv2'
  | 'eventShop'
  | 'exactTime'
  | 'reportTime'
  | 'reportDate';

export interface TimeShowProps {
  dateIsoString?: string | null;
  format?: string;
  type?: TimeShowType | string;
  className?: string;
}

export function TimeShow({ dateIsoString, format, type, className }: TimeShowProps) {
  const utcEnabled = useUserStore((s) => s.siteConfig?.utcEnabled ?? false);

  const date = useMemo(() => {
    if (utcEnabled) {
      return moment.parseZone(dateIsoString);
    } else {
      return moment(dateIsoString);
    }
  }, [dateIsoString, utcEnabled]);

  const getExactDateAndTime = () => {
    const d = moment.parseZone(dateIsoString);
    const formattedDate = d.format('YYYY-MM-DD HH:mm:ss');

    if (d.year() === moment().year()) {
      return d.format('MM-DD HH:mm:ss');
    }

    return formattedDate;
  };

  const getExactDate = () => {
    const d = moment.parseZone(dateIsoString);
    const formattedDate = d.format('YYYY-MM-DD');
    return formattedDate;
  };

  const getExactTime = () => {
    const d = moment.parseZone(dateIsoString);
    const formattedDate = d.format('HH:mm:ss');
    return formattedDate;
  };

  const getDateAndTimeFromISOString = () => {
    if (date.year() === 1970 || date.year() === 1969) {
      return '-';
    }

    if (format) {
      return date.format(format);
    }
    if (date.year() === moment().year()) {
      return date.format('MM-DD HH:mm:ss');
    }
    return date.format('YYYY-MM-DD HH:mm:ss');
  };

  if (type === 'inFields') {
    return (
      <div className={className}>
        <h3 style={{ color: '#666666', fontWeight: 400, fontSize: '14px' }}>
          {date.format('HH:mm:ss')}
        </h3>
        <div style={{ fontSize: '12px', color: 'rgba(113, 113, 113, 1)' }}>
          {date.format('YYYY-M-D')}
        </div>
      </div>
    );
  }

  if (type === 'withoutSec') {
    return <div className={className}>{date.format('YYYY-M-D HH:mm')}</div>;
  }

  if (type === 'GMTinFields') {
    return (
      <div className={className}>
        <div style={{ color: '#4d4d4d', fontWeight: 400, fontSize: '14px' }}>
          {getExactTime()}
        </div>
        <div style={{ fontSize: '12px', color: 'rgba(113, 113, 113, 1)' }}>
          {getExactDate()}
        </div>
      </div>
    );
  }

  if (type === 'GMToneLiner') {
    return (
      <div className={className}>
        <span>{getExactDateAndTime()}</span>
      </div>
    );
  }

  if (type === 'oneLiner') {
    return <div className={className}>{date.format('YYYY-M-D HH:mm:ss')}</div>;
  }

  if (type === 'customCSS') {
    return (
      <div className={className}>
        <span>{date.format('YYYY-M-D HH:mm:ss')}</span>
      </div>
    );
  }

  if (type === 'customCSSv2') {
    return (
      <div className={className}>
        <span>{date.format('YYYY-M-D')}</span>
      </div>
    );
  }

  if (type === 'eventShop') {
    return <span className={className}>{date.format('YYYY-M-D')}</span>;
  }

  if (type === 'exactTime') return <span className={className}>{getExactDateAndTime()} GMT</span>;
  if (type === 'reportTime') return <span className={className}>{getExactDateAndTime()}</span>;
  if (type === 'reportDate') return <span className={className}>{getExactDate()}</span>;

  return <span className={className}>{getDateAndTimeFromISOString()}</span>;
}

// app/web/vue/src/components/TimeShow.vue
<template>
  <div v-if="type === 'inFields'">
    <h3 style="color: #666666; font-weight: 400; font-size: 14px">
      {{ date.format("HH:mm:ss") }}
    </h3>
    <div style="font-size: 12px; color: rgba(113, 113, 113, 1)">
      {{ date.format("YYYY-M-D") }}
    </div>
  </div>
  <div v-else-if="type === 'withoutSec'">
    {{ date.format("YYYY-M-D HH:mm") }}
  </div>
  <div v-else-if="type === 'GMTinFields'">
    <div style="color: #4d4d4d; font-weight: 400; font-size: 14px">
      {{ getExactTime() }}
    </div>
    <div style="font-size: 12px; color: rgba(113, 113, 113, 1)">
      {{ getExactDate() }}
    </div>
  </div>
  <div v-else-if="type === 'GMToneLiner'">
    <span>{{ getExactDateAndTime() }}</span>
  </div>
  <!--style="font-size: 12px; color: rgba(113, 113, 113, 1)"-->
  <div v-else-if="type === 'oneLiner'">
    {{ date.format("YYYY-M-D HH:mm:ss") }}
  </div>
  <div v-else-if="type === 'customCSS'">
    <span>{{ date.format("YYYY-M-D HH:mm:ss") }}</span>
  </div>
  <div v-else-if="type === 'customCSSv2'">
    <span>{{ date.format("YYYY-M-D") }}</span>
  </div>
  <div v-else-if="type === 'eventShop'">
    <span>{{ date.format("YYYY-M-D") }}</span>
  </div>
  <!-- use  -->
  <span v-else-if="type === 'exactTime'">{{ getExactDateAndTime() }} GMT</span>
  <span v-else-if="type === 'reportTime'">{{ getExactDateAndTime() }}</span>
  <span v-else-if="type === 'reportDate'">{{ getExactDate() }}</span>
  <span v-else>{{ getDateAndTimeFromISOString() }}</span>
</template>

<script setup lang="ts">
import moment from "moment";
import { useStore } from "@/store";
import { computed } from "vue";

const props = defineProps<{
  dateIsoString: string | null | undefined;
  format?: string;
  type?: string;
}>();

const store = useStore();

const date = computed(() => {
  // const regex = /\.\d+Z$/;
  // let str = props.dateIsoString;
  // console.log(str);
  // if (regex.test(str)) {
  //   str = str.slice(0, -5);
  //   console.log(str);
  // }
  // return moment(str).locale(store.state.AuthModule.user.language);
  // return moment(props.dateIsoString).locale(
  //   store.state.AuthModule.user.language
  // );
  if (store.state.AuthModule.config.utcEnabled) {
    return moment.parseZone(props.dateIsoString);
  } else {
    return moment(props.dateIsoString);
    //return moment.parseZone(props.dateIsoString);
  }
});

const getExactDateAndTime = () => {
  const date = moment.parseZone(props.dateIsoString);
  const formattedDate = date.format("YYYY-MM-DD HH:mm:ss");

  if (date.year() === moment().year()) {
    return date.format("MM-DD HH:mm:ss");
  }

  return formattedDate;
};

const getExactDate = () => {
  const date = moment.parseZone(props.dateIsoString);
  const formattedDate = date.format("YYYY-MM-DD");
  return formattedDate;
};

const getExactTime = () => {
  const date = moment.parseZone(props.dateIsoString);
  const formattedDate = date.format("HH:mm:ss");
  return formattedDate;
};

const getDateAndTimeFromISOString = () => {
  if (date.value.year() === 1970 || date.value.year() === 1969) {
    return "-";
  }

  // const now = moment().locale(useStore().state.AuthModule.user.language);
  // const threeDaysAgo = now.clone().subtract(5, "days");

  // if (date.isBetween(threeDaysAgo, now)) {
  //   return date.fromNow();
  // }

  // return date.locale(useStore().state.AuthModule.user.language).fromNow();
  if (props.format) {
    return date.value.format(props.format);
  }
  if (date.value.year() === moment().year()) {
    return date.value.format("MM-DD HH:mm:ss");
  }
  return date.value.format("YYYY-MM-DD HH:mm:ss");
};
</script>

<style scoped></style>
